const PDFDocument = require("pdfkit");

async function generateBillPdf(bill) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      let buffers = [];

      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      generateHeader(doc);

      generateCustomerInfo(doc, bill);

      generateBillTableContent(doc, bill);

      generateFooter(doc);

      doc.end();
    } catch (err) {
      console.error("generating PDF:", err);
      reject(err);
    }
  });
}

// GENERATE BILL HEADER
function generateHeader(doc) {
  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("INVOICE", 50, 57)
    .fontSize(10)
    .font("Helvetica")
    .text(`Bill generated on : ${new Date(Date.now()).toLocaleString()}`, 200, 57, { align: "right" })
    .text("", 200, 80, { align: "right" })
    .moveDown();
}

// GENERATE BILL FOOTER
function generateFooter(doc) {
  doc
    .fontSize(10)
    .font("Helvetica")
    .text("This document is generated by hobby project app; it is absolutely NOT FOR COMMERCIAL USE.", 50, 775, {
      align: "center",
      width: 500,
    });
}

// GENERATE HORIZONTAL LINE
function generateLine(doc, color, lineWidth, y) {
  doc.strokeColor(color).lineWidth(lineWidth).moveTo(50, y).lineTo(550, y).stroke();
}

// GENERATE SINGLE TABLE ROW
function generateTableRow(doc, y, fontSize, fontStyle, column1, column2, column3, column4, column5) {
  doc
    .fontSize(fontSize)
    .font(fontStyle)
    .text(column1, 50, y)
    .text(column2, 230, y, { width: 60, align: "center" })
    .text(column3, 280, y, { width: 90, align: "right" })
    .text(column4, 370, y, { width: 90, align: "right" })
    .text(column5, 0, y, { align: "right" });
}

// GENERATE CUSTOMER INFO
function generateCustomerInfo(doc, bill) {
  generateLine(doc, "#aaaaaa", 1, 135);

  const y = 150;

  doc.fontSize(10).font("Helvetica-Bold").text("Invoice Number:", 50, y).font("Helvetica").text(`${bill._id}`, 150, y);

  doc
    .font("Helvetica-Bold")
    .text("Customer Name:", 50, y + 15)
    .font("Helvetica")
    .text(`${bill.customerName}`, 150, y + 15);

  doc
    .font("Helvetica-Bold")
    .text("Purchased Date", 50, y + 30)
    .font("Helvetica")
    .text(`${bill.createdAt.toLocaleDateString()}`, 150, y + 30);

  doc.font("Helvetica-Bold").text("Total Item:", 300, y).font("Helvetica").text(`${bill.totalItems}`, 400, y);

  doc
    .font("Helvetica-Bold")
    .text("Total Amount:", 300, y + 15)
    .font("Helvetica")
    .text(`${bill.totalAmount.toFixed(2)}  Rs`, 400, y + 15);

  doc
    .font("Helvetica-Bold")
    .text("Total Savings:", 300, y + 30)
    .font("Helvetica")
    .text(`${bill.totalSavings.toFixed(2)}  Rs`, 400, y + 30)
    .moveDown();

  generateLine(doc, "#aaaaaa", 1, 202);
}

// GENERATE BILL TABLE CONTENT
function generateBillTableContent(doc, bill) {
  const invoiceTableTopMargin = 250;
  let i = 0;

  generateTableRow(
    doc,
    invoiceTableTopMargin,
    11,
    "Helvetica-Bold",
    "Item Name",
    "Quantity",
    "Price",
    "Discount",
    "Selling Price"
  );

  generateLine(doc, "#aaaaaa", 1, invoiceTableTopMargin + 20);

  bill.items.forEach((item) => {
    const position = invoiceTableTopMargin + (i + 1) * 30;
    generateTableRow(
      doc,
      position,
      10,
      "Helvetica",
      item.name,
      item.quantity,
      `${item.price.toFixed(2)} Rs`,
      `${item.discount || "-"} %`,
      `${item.sellingPrice.toFixed(2)} Rs`
    );
    i++;
    generateLine(doc, "#aaaaaa", 1, position + 20);
  });

  const totalAmountPosition = invoiceTableTopMargin + (i + 1) * 31;
  generateTableRow(
    doc,
    totalAmountPosition,
    10,
    "Helvetica-Bold",
    "",
    "",
    "",
    "Total Amount:",
    `${bill.totalAmount.toFixed(2)} Rs`
  );

  const totalSavingsPositions = totalAmountPosition + 20;
  generateTableRow(
    doc,
    totalSavingsPositions,
    10,
    "Helvetica-Bold",
    "",
    "",
    "",
    "Total Savings:",
    `${bill.totalSavings.toFixed(2)} Rs`
  );
}

module.exports = generateBillPdf;
